config/routes.rb
Rails.application.routes.draw do
  root to: 'dashboard#index'
  get "/dashboard" => "dashboard#index"
  get "/search" => "projects#search"
  resources :users, controller: 'users' do
    resource :password, controller: 'clearance/passwords', only: [:create, :edit, :update]
    resources :instant_messages, only: [:create, :index]
  end

  resources :projects do
    resources :groups
  end
  resources :tasks do
  	member do
  		put :toggle
  	end
  end
end

app/models/group.rb
class Group < ActiveRecord::Base
  mount_uploader :banner, BannerUploader
  has_many :user_groups, dependent: :destroy
	has_many :users, through: :user_group
	has_many :user_group
  has_many :tasks
  has_many :instant_messages
	belongs_to :project
end

app/models/instant_message.rb
class InstantMessage < ActiveRecord::Base
	belongs_to :sending_user, class_name: "User", foreign_key: "user_id_sent"
	belongs_to :receiving_user, class_name: "User", foreign_key: "user_id_received"
	validates :text, presence: true

	def str_time
		#verifica se esta no fuso horario de verao
		# if self.time.between?(DateTime.new(2015,05,29), DateTime.new(2015,10,25)) 
		# 	self.time += 1.hour
		# end 

		#verifica se esta no mesmo dia
		if DateTime.now.strftime("%d/%m/%Y") == self.time.strftime("%d/%m/%Y")
			hours_message = self.time.hour + self.time.min/60.0 + self.time.sec/3600.0 # passar tudo para horas
			hours_now = DateTime.now.hour + DateTime.now.min/60.0 + DateTime.now.sec/3600.0
			dif_minutes = ((hours_message - hours_now)*60).abs
			if dif_minutes < 1 
				return "now"
			elsif dif_minutes.between?(1,59)
				return "#{dif_minutes.round} min"
			else
				return self.time.strftime("%H:%M")
			end	
		end

		#verifica se esta na mesmo semana 
		return self.time.strftime("%a, %H:%M") if
			self.time.between?(self.time.at_beginning_of_week, self.time.at_end_of_week) 

		# se nenhuma das condicoes se verificar
		return self.time.strftime("%d de %b, %H:%M")
	end
end

app/models/project.rb
class Project < ActiveRecord::Base
	has_many :groups, dependent: :destroy
end

app/models/task.rb
class Task < ActiveRecord::Base
	belongs_to :users
  belongs_to :group
end

app/models/user.rb
class User < ActiveRecord::Base
include Clearance::User

  mount_uploader :avatar, AvatarUploader
	has_many :user_groups
	has_many :groups, through: :user_groups
	has_many :tasks
	has_many :sent_messages, class_name: "InstantMessage", foreign_key: "user_id_sent"
	has_many :received_messages, class_name: "InstantMessage", foreign_key: "user_id_received"
  
end

app/models/user_group.rb
class UserGroup < ActiveRecord::Base
	belongs_to :group
	belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
  protect_from_forgery with: :exception

  before_action :initialize_project

  def initialize_project
    @project = Project.new
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    if signed_in?
      @projects = Project.all
      @users = User.all
      @groups = Group.all
      @tasks = Task.all
      @project = Project.new
    else
      redirect_to sign_in_path
    end
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  def new
    @project = Project.find(params[:project_id])
  	@group = Group.new
  end

  def create
    @project = Project.find(params[:project_id])
  	group = @project.groups.build(group_params)
    group.user_ids = params[:group][:user_ids]
    group.save
  	redirect_to project_groups_path
  end

  def show
  	@group = Group.find(params[:id])
  end

  def edit
    @project = Project.find(params[:project_id])
  	@group = Group.find(params[:id])
  end

  def update
  	Group.find(params[:id]).update(group_params)
  	redirect_to project_groups_path
  end

  def destroy
  	Group.find(params[:id].to_i).destroy
  	redirect_to project_groups_path
  end

  def index
    @projects = Project.all
    @project = Project.find(params[:project_id])
    @groups = @project.groups
    @users = User.all
  end

  private
  def group_params
  	params.require(:group).permit(:name, :description, :banner)
  end
end

app/controllers/instant_messages_controller.rb
class InstantMessagesController < ApplicationController

	def index
		@user_received = User.find(params[:user_id])
		messages_user_sent = InstantMessage.where(user_id_sent: current_user.id, user_id_received: params[:user_id])
		messages_user_received = InstantMessage.where(user_id_sent: params[:user_id], user_id_received: current_user.id )
		@messages = [messages_user_sent, messages_user_received].flatten!.sort_by(&:time)
	end

	def create
		unless params[:instant_message][:text].empty?
			message = InstantMessage.new({
				text: params[:instant_message][:text],
				user_id_sent: current_user.id ,
				user_id_received: params[:user_id],
				time: DateTime.now
				})
			if message.save
				puts message.text
				redirect_to user_instant_messages_path
			else
				flash[:error] = "Action failed"
			end
		else
			redirect_to user_instant_messages_path
		end
	end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def new
    @project = Project.new
  end
  def create
    @project = Project.create ({
      name: params[:project][:name],
      description: params[:project][:description]
      })
    redirect_to dashboard_path
  end
  def edit
    @project = Project.find params[:id]
  end
  def update
    @project = Project.find params[:id]
    @project.update({
      name: params[:project][:name],
      description: params[:project][:description]
      })
    redirect_to dashboard_path
  end
  def destroy
    @project = Project.find params[:id]
    @project.destroy
    redirect_to dashboard_path
  end
  def show
    @project = Project.find params[:id]
  end
  def search
    if !params[:search].blank?
      @projects = Project.where('name LIKE ?', "%#{params[:search]}%")
    else
      @projects = Project.all
    end

    render json: @projects.map {|project| project.attributes.merge(avatar: current_user.avatar.url, username: current_user.first_name)}
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

	def new
    group = Group.find(params[:group_id])
    @task = group.tasks.build
  end

	def create
		task = Task.create(task_params)
		redirect_to project_groups_path({project_id: task.group.project.id})
	end

	def edit
		@task = Task.find(params[:id].to_i)
	end

	def update
		task = Task.find(params[:id].to_i)
    task.update(task_params)
		redirect_to project_groups_path({project_id: task.group.project.id})
	end

	def destroy
    task = Task.find(params[:id].to_i).destroy
    @group = task.group
    render "groups/group_tasks"
  	end

  def toggle
  	task = Task.find(params[:id].to_i)
  	task.status = !task.status
  	task.save
    @group = task.group
    render "groups/group_tasks"
  end

	private

    def task_params
    	params.require(:task).permit(:field, :group_id).merge(user_id: current_user.id)
    end
end

app/controllers/users_controller.rb
class UsersController < Clearance::UsersController
  def show
    @user = User.find do |user|
      user.id == params[:id].to_i
    end
  end
  def edit
    @user = User.find(params[:id])
  end
  def update
    @user = User.update(params[:id], update_user)
    redirect_to dashboard_path
    # redirect_to edit_user_path(current_user.id)
  end
  def destroy
    User.destroy(params[:id])
    redirect_to sign_in_path
  end
  def user_from_params
    first_name = user_params.delete(:first_name)
    last_name = user_params.delete(:last_name)
    email = user_params.delete(:email)
    password = user_params.delete(:password)

    Clearance.configuration.user_model.new(user_params).tap do |user|
      user.first_name = first_name
      user.last_name = last_name
      user.email = email
      user.password = password
    end
  end

  private

  def update_user
    params.require(:user).permit(:first_name, :last_name, :email , :password, :avatar)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/inst_message_helper.rb
module InstMessageHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/dashboard/_chat.erb
<div class="row chat-window col-xs-5 col-md-3" id="chat_window_1" style="margin-left:10px;">
  <div class="col-xs-12 col-md-12">
    <div class="panel panel-default">
      <div class="panel-heading top-bar panel-heading-open">
        <div class="col-md-8 col-xs-8">
          <h3 class="panel-title">
            <span class="glyphicon glyphicon-comment"></span>
            Chat - Miguel</h3>
        </div>
        <div class="col-md-4 col-xs-4" style="text-align: right;">
          <a href="#">
            <span class="glyphicon glyphicon-minus icon_minim" id="minim_chat_window"></span>
          </a>
          <a href="#">
            <span class="glyphicon glyphicon-remove icon_close" data-id="chat_window_1"></span>
          </a>
        </div>
      </div>
      <div class="panel-body msg_container_base">
        <div class="row msg_container base_sent">
          <div class="col-md-10 col-xs-10">
            <div class="messages msg_sent">
              <p>that mongodb thing looks good, huh? tiny master db, and huge document store</p>
              <time datetime="2009-11-13T20:00">Timothy • 51 min</time>
            </div>
          </div>
          <div class="col-md-2 col-xs-2 avatar">
            <img class=" img-responsive " src="https://a2.muscache.com/defaults/user_pic-50x50.png?v=2">
          </div>
        </div>
        <div class="row msg_container base_receive">
          <div class="col-md-2 col-xs-2 avatar">
            <img class=" img-responsive " src="https://a2.muscache.com/defaults/user_pic-50x50.png?v=2">
          </div>
          <div class="col-md-10 col-xs-10">
            <div class="messages msg_receive">
              <p>that mongodb thing looks good, huh? tiny master db, and huge document store</p>
              <time datetime="2009-11-13T20:00">Timothy • 51 min</time>
            </div>
          </div>
        </div>
        <div class="row msg_container base_sent">
          <div class="col-xs-10 col-md-10">
            <div class="messages msg_sent">
              <p>that mongodb thing looks good, huh? tiny master db, and huge document store</p>
              <time datetime="2009-11-13T20:00">Timothy • 51 min</time>
            </div>
          </div>
          <div class="col-md-2 col-xs-2 avatar">
            <img class=" img-responsive " src="https://a2.muscache.com/defaults/user_pic-50x50.png?v=2s">
          </div>
        </div>
      </div>
      <div class="panel-footer">
        <div class="input-group">
          <input  class="form-control input-sm chat_input" id="btn-input" placeholder="Send a message" type="text"/>
          <!-- <span class="input-group-btn">
            <button class="btn btn-primary btn-sm" id="btn-chat">Send</button>
          </span> -->
        </div>
      </div>
    </div>
  </div>
</div>

app/views/dashboard/index.erb
<div class="col s4">
  <div class="show-project-container">
    <div class="name-project-container">
      <h5>Projects List</h5>
    </div>
    <div class="list-projects-container">
      <% @projects.each do |project| %>
      <div class="row">
       <div class="s12">
        <%= link_to project_groups_path(project), class: 'collection-item' do %>
        <div class="col s6">
          <div class="project-name">
            <h5><%= project.name %></h5>
          </div>
        </div>
        <% end %>
        <div class="project-index-buttons">
          <%= link_to project_path(project) do %>
          <button class="btn waves-effect waves-light">Details</button>
          <% end %>
          <%= link_to edit_project_path(project) do %>
          <button class="btn waves-effect waves-light">Edit</button>
          <% end %>
          <%= link_to project_path(project), method: :delete do %>
          <button class="btn waves-effect waves-light"><i class="material-icons">delete</i></button>
          <% end %>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>
</div>

<%= render "/projects/new" %>

app/views/group/edit.erb
<div class="form-edit_group">
  <h3>Edit Group:</h3>
    <!-- o user_id tem de ser passado dependendo do login do user -->
  <form action="/group/<%=@group.id%>/update/1" method='post'>
    <div>
      <label for="field">Group name:</label>
    </div>
    <div>
      <input name="name" type="text" value="<%= @group.name %>">

      <div>
      <label for="field">Group description:</label>
    </div>

      <input name="description" type="text" value="<%= @group.description %>">
    </div>

    <div>
      <button type='submit'>update group</button>
    </div>
  </form>
</div>

app/views/group/new.erb
<div class="form-create_groups">
	<h3>Create new group</h3>
	<form action="/group/create" method="post">
		<input type="text" name="name" placeholder="Insert your name here" required>
		<input type="text" name="description" placeholder="Insert description here" required>
		<button type="submit">Create group</button>
	</form>
</div>

app/views/group/show.erb
<div class="container-list-groups">
	<h3> List all Groups </h3>
	<ul class="list-groups">
		<% @groups.each do |group| %>
			<li>
				<%= group.name %>
				<a href="/group/<%= group.id %>/remove"><button>Remove group</button></a>
			</li>
      <!-- ************************ -->
      <li>
        <a href="/group/<%= group.id %>/edit"><button>Edit group</button></a>
      </li>
      <!-- ************************ -->
		<% end %>
	</ul>
</div>

app/views/groups/_group_tasks.erb
<span class="card-title grey-text text-darken-4">
  Task's
  <i class="material-icons right">close</i>
</span>

<br>

<div class="listTask">
  <table class="hoverable">
    <thead><tr><th data-field="id">To-Do:</th></tr></thead>
    <% group.tasks.each do |task| %>
      <% if task.status == false %>
        <tbody>
          <tr>
            <td><%= task.field %></td>
            <td><%= link_to 'Done', toggle_task_path(task), remote: true, method: :put %></td>
            <td><%= link_to 'Edit', edit_task_path(task) %></td>
          </tr>
        </tbody>
      <% end %>
    <% end %>
  </table><br>

  <table class="hoverable">
    <thead><tr><th data-field="id">Done:</th></tr></thead>
    <% group.tasks.each do |task| %>
      <% if task.status == true %>
        <tbody>
          <tr>
            <td><%= task.field %></td>
            <td><%= link_to 'Not Done', toggle_task_path(task), remote: true, method: :put %></td>
            <td>
              <%= link_to task_path(task), remote: true, method: :delete do %>
                <i class="material-icons">delete</i>
              <% end %>
            </td>
          </tr>
        </tbody>
      <% end %>
    <% end %>
  </table><br>
</div>

app/views/groups/create.erb
<div class="form-create_groups">
	<h3>Create new group</h3>
	<form action="/group/create" method="post">
		<input type="text" name="name" placeholder="Insert your name here">
		<input type="text" name="description" placeholder="Insert description here">
		<select>
			<option>Elements</option>
			<% @users.each do |user| %>
			<option name='element' value='#{<%= user.id %>}'>
				<%= user.first_name %>
			</option>
			<%end%>
		</select>
		<button type="submit">Create group</button>
	</form>
</div>

app/views/groups/edit.erb
<div class="col s4">
	<div class="edit-group-container">
		<div class="name-edit-group-container">
			<h5>Edit Group</h5>
		</div>
		<div class="col s12">
			<div class="row">
				<%= form_for [@project, @group] do |f| %>
					<%= f.label :name %>
					<%= f.text_field :name, class: "validate" %>
					<%= f.label :description %>
					<%= f.text_field :description, class: "validate" %>
					Group Image:
					<%= f.file_field :banner %>
					<button class="btn waves-effect waves-light" type="submit"><% f.submit %>Update</button>
				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/groups/group_form-create.erb
<div class="form-create_groups">
	<h3>Create new group</h3>
	<form action="/group/create" method="post">
		<input type="text" name="name" placeholder="Insert your name here">
		<input type="text" name="description" placeholder="Insert description here">
		<select>
			<option>Elements</option>
			<% @users.each do |user| %>
			<option name='element' value='#{<%= user.id %>}'>
				<%= user.first_name %>
			</option>
			<%end%>
		</select>
		<button type="submit">Create group</button>
	</form>
</div>

app/views/groups/group_list.erb
<div class="container-list-groups">
	<h3> List all Groups </h3>
	<ul class="list-groups">
		<% @groups.each do |group| %>
			<li>
				<%= group.name %>
				<a href="/group/<%= group.id %>/remove"><button>Remove group</button></a>
			</li>
		<% end %>
	</ul>
</div>

app/views/groups/group_tasks.js.erb
$('#tasks-editor-<%= @group.id %>').html('<%= escape_javascript render("/groups/group_tasks", group: @group) %>');
console.log("ERROR")

app/views/groups/index.erb
<div class="new_group"><br>
  <button class="new_group_button">
    <%= link_to 'New group', new_project_group_path(@project), class: "waves-effect waves-light btn" %>
  </button>
</div><br>

<% if !@groups.empty? %>

<div class="row">
  <% @groups.each do |group| %>
  <div class="col s4">
    <div class="card medium">
      <div class="card-image waves-effect waves-block waves-light">
        <%= image_tag group.banner.url, class: "activator" %>
      </div>
<!-- ***********CARD CONTENT********* -->
      <div class="card-content">
        <span class="card-title activator grey-text text-darken-4">
          <%= link_to group.name, project_group_path(@project, group.id) %>
          <% if !group.tasks.empty? %>
          <i class="material-icons right">list</i>
          <% end %>
        </span>

        <div class="newTask">
          <%= link_to new_task_path(group_id: group.id) do %>
          <button class="btn waves-effect waves-light">New Task</button>
          <% end %>
          <%= link_to edit_project_group_path(@project, group) do %>
          <button class="btn waves-effect waves-light">Edit</button>
          <% end %>

          <%= link_to project_group_path(@project, group), :method => :delete do %>
          <button class="btn waves-effect waves-light">
            <i class="material-icons">delete</i>
          </button>
          <% end %>
        </div>
      </div>
<!-- ***********CARD CONTENT TASK'S********* -->
      <% if !group.tasks.empty? %>
        <div id="tasks-editor-<%= group.id %>" class="card-reveal">
           <%= render "/groups/group_tasks", group: group %>
      </div>
      <% end %>
    </div>
<!-- div card medium -->
  </div>
<!-- div col s4 -->
  <% end %>
</div>
<!-- div row -->
<% end %>

<div class="fixed-action-btn" style="bottom: 45px; right:24px;">
  <a class="btn-floating btn-large red">
    <i class="material-icons">chat</i>
  </a>
  <ul id="users-list">
    <% unless @users.empty? %>
    <% @users.each do |user| %>
    <li>
      <% if user.first_name.downcase != current_user.first_name.downcase %>
        <%= link_to user_instant_messages_path({user_id: user.id}), remote: true, class: "btn-floating", style: "transform: scaleY(0.4) scaleX(0.4) translateY(40px); opacity: 0;"  do %>
          <i class="name_user"><img src="<%= user.avatar.url %>" alt=""> </i>
        <% end %>
      <% end %>
    </li>
    <%end%>
    <% end %>
  </ul>
</div>

app/views/groups/new.erb
<div class="col s4">
	<div class="edit-group-container">
		<div class="name-create-group-container">
			<h5>Create new group</h5>
		</div>
		<div class="create-group-container">
		<div class="col s12">
				<div class="row">
					<%= form_for [@project, @group] do |f| %>
					<%= f.label :name %>
					<%= f.text_field :name, class: "validate" %>
					<%= f.label :description %>
					<%= f.text_field :description, class: "validate" %>
					<%# f.collection_check_boxes(:user_ids, User.all, :id, :first_name) %>
					<button class="btn waves-effect waves-light" type="submit"><% f.submit %>Create</button>
					<% end %>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/groups/show.erb
<div class="col s4">
	<div class="group-show-container">
		<div class="name-show-group-container">
		<h5>Group Info</h5>
		</div>
		<div class="col s12">
			<div class="row">
				<h5>Group name</h5>
				<%= @group.name %>
				<h5>Description</h5>
				<%= @group.description %>
				<h5>Users</h5>
				<% User.all.each do |user| %>
				<%= user.first_name %>
				<%= user.last_name %>
				<% end %>
			</div>	
		</div>
	</div>
</div>
</div>

app/views/instant_messages/_chat.erb
<div class="col-xs-12 col-md-12">
  <div class="panel panel-default">
    <div class="panel-heading top-bar panel-heading-open">
      <div class="col-md-8 col-xs-8">
        <h3 class="panel-title">
          <span class="glyphicon glyphicon-comment"></span>
          <%= user_received.first_name %> <%= user_received.last_name %>
        </h3>
      </div>
      <div class="col-md-4 col-xs-4" style="text-align: right;">
        <a href="#">
          <span class="glyphicon glyphicon-minus icon_minim" id="minim_chat_window"></span>
        </a>
        <a href="#">
          <span class="glyphicon glyphicon-remove icon_close" data-id="chat_window_1"></span>
        </a>
      </div>
    </div>
    <div class="panel-body msg_container_base">
    <% messages.each do |m| %>
      <% if m.user_id_sent == current_user.id %>
        <div class="row msg_container base_sent">
          <div class="col-md-10 col-xs-10">
            <div class="messages msg_sent">
              <p><%= m.text %></p>
              <time><%= current_user.first_name%> • <%= m.str_time %></time>
            </div>
          </div>
          <div class="col-md-2 col-xs-2 avatar">
            <img class=" img-responsive " src="<%= current_user.avatar.url %>">
          </div>
        </div>
        <% else %>
        <div class="row msg_container base_receive">
          <div class="col-md-2 col-xs-2 avatar">
            <img class=" img-responsive " src="<%= user_received.avatar.url %>">
          </div>
          <div class="col-md-10 col-xs-10">
            <div class="messages msg_receive">
              <p><%= m.text %></p>
              <time><%= user_received.first_name%> • <%= m.str_time %></time>
            </div>
          </div>
        </div>
      <% end %>
    <%end%>
    </div>
    <div class="panel-footer">
      <div class="input-group">
        <%= form_for :instant_message, url: user_instant_messages_path({user_id: user_received.id}), method: :post, remote: true, id: "send-message-form" do |f| %>
          <%= f.text_field :text, class:'form-control input-sm chat_input', id:'btn-input', placeholder: 'Send a message' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
  $('#send-message-form').submit(function() {
    $(this).unbind('submit').submit();
  });
</script>

app/views/instant_messages/index.js.erb
$('#chat_window_1').html('<%= escape_javascript render("/instant_messages/chat", user_received: @user_received, messages: @messages) %>');

app/views/project/edit.erb
<div class="container project-edit">
	<h3>Edit Project</h3>
	<form action="/project/<%=@project.id%>/update" method="post">
		<input type = "text" name = "name" value = "<%=@project.name%>">
		<input type = "text" name = "description" value = "<%=@project.description%>">
		<button type = "submit">Create Project</button>
	</form>
</div>

app/views/project/new.erb
<div class="container project-new">
	<h3>Create Project</h3>
	<form action="/project/create" method="post">
		<input type="text" name="name" placeholder="Insert your name here" required>
		<input type="text" name="description" placeholder="Insert description here" required>
		<button type="submit">Create Project</button>
	</form>
</div>

app/views/project/show.erb
<div class="container-list-groups">
	<h3> List all Projects </h3>
	<ul class="list-groups">
		<% @projects.each do |project| %>
			<li>
				<%= project.name %>
				<a href="/project/<%= project.id %>/remove"><button>Remove project</button></a>
				<a href="/project/<%= project.id %>/edit"><button>Edit project</button></a>
			</li>
		<% end %>
	</ul>
</div>

app/views/projects/_new.html.erb
<div class="modal" id="modal-add-project">
  <div class="modal-content">
    <div class="body-panel">
      <%= form_for @project do |f| %>

      <div class="body-panel-header">
        Create Project
      </div>
      <div class="body-panel-body">
        <div class="row">
          <div class="input-field col s12">
            <%= f.label :name %>
            <%= f.text_field :name %>
          </div>
        </div>
        <div class="row">
          <div class="input-field col s12">
            <%= f.text_area :description, class: 'materialize-textarea' %>
            <%= f.label :description %>
          </div>
        </div>
      </div>
      <div class="body-panel-footer">
        <%= link_to "#" , class: "btn waves-effect waves-light back-button modal-action modal-close" do %>
        Back
        <i class="material-icons left">replay</i>
        <% end %>
        <%= f.button 'CREATE PROJECT' , class: 'btn waves-effect waves-light' %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/projects/new.erb
<%= render "new" %>

app/views/tasks/edit.erb
<div class="col s6">
	<div class="task-new-edit-container">
		<%= form_for :task, url: task_path(@task), method: :patch do |f| %>
		<div class="col s12">
			<div class="row">
				<div class="input-field">
					<i class="material-icons prefix">assignment</i>
					<%= f.text_field :field %>
					<%= f.label :field %>
				</div>
			</div>
		</div>
		<div class="button-edit-task">
			<a class="waves-effect waves-light btn"><%= f.submit %></a>
		</div>
		<% end %>
	</div>
</div>

app/views/tasks/new.erb
<div class="col s6">
	<div class="task-new-edit-container">
		<%= form_for @task, url: tasks_path do |f| %>
      <%= f.hidden_field :group_id %>
			<div class="col s12">
				<div class="row">
					<div class="input-field">
						<i class="material-icons prefix">assignment</i>
						<%= f.text_field :field %>
						<%= f.label :field %>
					</div>
				</div>
			</div>
			<div class="button-edit-task">
				<a class="waves-effect waves-light btn"><%= f.submit %></a>
			</div>
		<% end %>
	</div>
</div>

app/views/users/edit.erb
<div class="container">
  <div class="user-panel">
    <%= form_for @user do |f| %>
    <div class="user-panel-header">
      Edit User
    </div>
    <div class="user-panel-body">
      <div class="row">
        <div class="col s6">
          <div class="profile-background-container">
            <div class="media-photo profile-picture">
                <img src="<%= @user.avatar.url %>">
            </div>
            <div class="media-photo media-round">
              <img src="<%= @user.avatar.url %>">
            </div>
          </div>
        </div>
        <div class="col s6">
          <div class="col s12">
            <div class="row">
              <div class="input-field col s12">
                <%= f.label :first_name %>
                <%= f.text_field :first_name, class: "validate" %>
              </div>
            </div>
            <div class="row">
              <div class="input-field col s12">
                <%= f.label :last_name %>
                <%= f.text_field :last_name, class: "validate" %>
              </div>
            </div>
            <div class="row">
              <div class="input-field col s12">
                <%= f.email_field :email, class: "validate" %>
                <%= f.label :email %>
              </div>
            </div>
            <div class="row">
              <div class="input-field col s12">
                <%= f.label :password %>
                <%= f.password_field :password, class: "validate"%>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col s4">
          <div class="button-upload">
          <%= f.file_field :avatar, title: "Upload Profile Picture" %>
          </div>
        </div>
      </div>
    </div>
    <div class="user-panel-footer">
      <%= link_to dashboard_path, class: "btn waves-effect waves-light back-button" do %>
      Back
      <i class="material-icons left">replay</i>
      <% end %>
      <%= f.button 'SAVE', class: 'btn waves-effect waves-light' %>
    </div>
    <% end %>
  </div>
</div>

<div class="container">
  <div class="user-panel">
    <div class="user-panel-header">
      Cancel Account
    </div>
    <div class="user-panel-body">
      <%= link_to user_path(@user.id), method: :delete, class: "btn waves-effect waves-light cancel-account-button" do %>
        Delete
      <% end %>
    </div>
  </div>
</div>